# 파이토치의 nn.Linear와 nn.Sigmoid로 로지스틱 회귀 구현하기

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim



In [14]:
torch.manual_seed(42)

In [15]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
print(x_train.shape, y_train.shape)


torch.Size([6, 2]) torch.Size([6, 1])


In [16]:
# nn.Sequential()은 nn.Module 층을 차례로 쌓을 수 있도록 해줌.
model = nn.Sequential(nn.Linear(2, 1), # input_dim = 2, output_dim = 1
                      nn.Sigmoid() # 출력은 시그모이드 함수를 거친다.
                      )

In [17]:
# 현재 nn.Linear의 W, b는 random 초기화된 상태
model(x_train)

tensor([[0.8247],
        [0.9356],
        [0.8852],
        [0.9772],
        [0.9866],
        [0.9860]], grad_fn=<SigmoidBackward0>)

In [30]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epoch = 1000
for epoch in range(nb_epoch + 1):
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch: {:4d}/{}, Cost: {:.6f}, Accuracy {:2.2f}%'.format(epoch, nb_epoch, cost.item(), accuracy * 100))

Epoch:    0/1000, Cost: 0.019760, Accuracy 100.00%
Epoch:   10/1000, Cost: 0.019579, Accuracy 100.00%
Epoch:   20/1000, Cost: 0.019401, Accuracy 100.00%
Epoch:   30/1000, Cost: 0.019227, Accuracy 100.00%
Epoch:   40/1000, Cost: 0.019055, Accuracy 100.00%
Epoch:   50/1000, Cost: 0.018887, Accuracy 100.00%
Epoch:   60/1000, Cost: 0.018721, Accuracy 100.00%
Epoch:   70/1000, Cost: 0.018559, Accuracy 100.00%
Epoch:   80/1000, Cost: 0.018399, Accuracy 100.00%
Epoch:   90/1000, Cost: 0.018242, Accuracy 100.00%
Epoch:  100/1000, Cost: 0.018088, Accuracy 100.00%
Epoch:  110/1000, Cost: 0.017936, Accuracy 100.00%
Epoch:  120/1000, Cost: 0.017787, Accuracy 100.00%
Epoch:  130/1000, Cost: 0.017640, Accuracy 100.00%
Epoch:  140/1000, Cost: 0.017496, Accuracy 100.00%
Epoch:  150/1000, Cost: 0.017354, Accuracy 100.00%
Epoch:  160/1000, Cost: 0.017214, Accuracy 100.00%
Epoch:  170/1000, Cost: 0.017077, Accuracy 100.00%
Epoch:  180/1000, Cost: 0.016941, Accuracy 100.00%
Epoch:  190/1000, Cost: 0.01680

In [29]:
print(model(x_train), model(x_train) >= torch.FloatTensor([0.5]))
print("\n", list(model.parameters()))

tensor([[2.7396e-04],
        [3.1498e-02],
        [3.8832e-02],
        [9.5637e-01],
        [9.9825e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>) tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])

 [Parameter containing:
tensor([[3.2566, 1.5198]], requires_grad=True), Parameter containing:
tensor([-14.4985], requires_grad=True)]


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(42)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


class BinaryClassfier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    
model = BinaryClassfier()

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().ite.m() / len(correct_prediction)
        print('Epoch: {:4d}/{}, Cost: {:.6f}, Accuracy: {:2.2f}'.format(epoch, nb_epochs, cost.item(), accuracy * 100))

Epoch:    0/1000, Cost: 1.116662, Accuracy: 50.00
Epoch:   10/1000, Cost: 1.017122, Accuracy: 66.67
Epoch:   20/1000, Cost: 0.549955, Accuracy: 83.33
Epoch:   30/1000, Cost: 0.452354, Accuracy: 83.33
Epoch:   40/1000, Cost: 0.367874, Accuracy: 83.33
Epoch:   50/1000, Cost: 0.288718, Accuracy: 83.33
Epoch:   60/1000, Cost: 0.220350, Accuracy: 83.33
Epoch:   70/1000, Cost: 0.173810, Accuracy: 100.00
Epoch:   80/1000, Cost: 0.151925, Accuracy: 100.00
Epoch:   90/1000, Cost: 0.140459, Accuracy: 100.00
Epoch:  100/1000, Cost: 0.131157, Accuracy: 100.00
Epoch:  110/1000, Cost: 0.123039, Accuracy: 100.00
Epoch:  120/1000, Cost: 0.115886, Accuracy: 100.00
Epoch:  130/1000, Cost: 0.109534, Accuracy: 100.00
Epoch:  140/1000, Cost: 0.103856, Accuracy: 100.00
Epoch:  150/1000, Cost: 0.098751, Accuracy: 100.00
Epoch:  160/1000, Cost: 0.094135, Accuracy: 100.00
Epoch:  170/1000, Cost: 0.089942, Accuracy: 100.00
Epoch:  180/1000, Cost: 0.086115, Accuracy: 100.00
Epoch:  190/1000, Cost: 0.082609, Accu