### Logistic Regression using nn.module

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [12]:
x_data = [[1,2],
          [2,3],
          [3,1],
          [4,3],
          [5,3],
          [6,2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [13]:
# sequatially compute Linear(Wx+b), then Sigmoid (1/(1+e^(-x)))
model = nn.Sequential(nn.Linear(2,1), nn.Sigmoid())

In [14]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [18]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        # make prediction
        prediction = hypothesis >= torch.FloatTensor([0.5])
        # check if the prediction is true or not
        TPN = prediction.float() == y_train
        # calculate acc value
        acc = TPN.sum().item() / len(TPN)

        print('Epoch {:4d}/{} Cost : {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), acc*100
        ))


Epoch    0/1000 Cost : 1.188488 Accuracy 50.00%
Epoch   10/1000 Cost : 0.648468 Accuracy 83.33%
Epoch   20/1000 Cost : 0.548321 Accuracy 83.33%
Epoch   30/1000 Cost : 0.456483 Accuracy 83.33%
Epoch   40/1000 Cost : 0.372049 Accuracy 83.33%
Epoch   50/1000 Cost : 0.292564 Accuracy 83.33%
Epoch   60/1000 Cost : 0.223404 Accuracy 83.33%
Epoch   70/1000 Cost : 0.175517 Accuracy 100.00%
Epoch   80/1000 Cost : 0.152655 Accuracy 100.00%
Epoch   90/1000 Cost : 0.140972 Accuracy 100.00%
Epoch  100/1000 Cost : 0.131600 Accuracy 100.00%
Epoch  110/1000 Cost : 0.123428 Accuracy 100.00%
Epoch  120/1000 Cost : 0.116229 Accuracy 100.00%
Epoch  130/1000 Cost : 0.109840 Accuracy 100.00%
Epoch  140/1000 Cost : 0.104131 Accuracy 100.00%
Epoch  150/1000 Cost : 0.098998 Accuracy 100.00%
Epoch  160/1000 Cost : 0.094360 Accuracy 100.00%
Epoch  170/1000 Cost : 0.090146 Accuracy 100.00%
Epoch  180/1000 Cost : 0.086302 Accuracy 100.00%
Epoch  190/1000 Cost : 0.082780 Accuracy 100.00%
Epoch  200/1000 Cost : 0.07

In [19]:
model(x_train)

tensor([[2.7427e-04],
        [3.1512e-02],
        [3.8850e-02],
        [9.5635e-01],
        [9.9824e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [21]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2561, 1.5196]], requires_grad=True), Parameter containing:
tensor([-14.4964], requires_grad=True)]


### Logistic Regression using class


In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [26]:
x_data = [[1,2],
          [2,3],
          [3,1],
          [4,3],
          [5,3],
          [6,2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [27]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    

model = BinaryClassifier()

In [28]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:

        prediction = hypothesis >= torch.FloatTensor([0.5])

        TPN = prediction.float() == y_train

        acc = TPN.sum().item() / len(TPN)

        print('Epoch {:4d}/{} Cost {:.6f} Acc {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), acc * 100
        ))
        

Epoch    0/1000 Cost 0.539713 Acc 83.33%
Epoch   10/1000 Cost 0.614852 Acc 66.67%
Epoch   20/1000 Cost 0.441875 Acc 66.67%
Epoch   30/1000 Cost 0.373145 Acc 83.33%
Epoch   40/1000 Cost 0.316358 Acc 83.33%
Epoch   50/1000 Cost 0.266094 Acc 83.33%
Epoch   60/1000 Cost 0.220498 Acc 100.00%
Epoch   70/1000 Cost 0.182095 Acc 100.00%
Epoch   80/1000 Cost 0.157299 Acc 100.00%
Epoch   90/1000 Cost 0.144091 Acc 100.00%
Epoch  100/1000 Cost 0.134272 Acc 100.00%
Epoch  110/1000 Cost 0.125769 Acc 100.00%
Epoch  120/1000 Cost 0.118297 Acc 100.00%
Epoch  130/1000 Cost 0.111680 Acc 100.00%
Epoch  140/1000 Cost 0.105779 Acc 100.00%
Epoch  150/1000 Cost 0.100483 Acc 100.00%
Epoch  160/1000 Cost 0.095704 Acc 100.00%
Epoch  170/1000 Cost 0.091369 Acc 100.00%
Epoch  180/1000 Cost 0.087420 Acc 100.00%
Epoch  190/1000 Cost 0.083806 Acc 100.00%
Epoch  200/1000 Cost 0.080486 Acc 100.00%
Epoch  210/1000 Cost 0.077425 Acc 100.00%
Epoch  220/1000 Cost 0.074595 Acc 100.00%
Epoch  230/1000 Cost 0.071969 Acc 100.00