# nn.Module과 클래스로 linear regression 구현하기 (single linear regression)

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [ ]:
# model = nn.Linear(input_dim, output_dim)
# cost = F.mse_loss(prediction, y_train)

In [4]:
torch.manual_seed(42)

In [6]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim = 1, ouypuy_dim = 1
model = nn.Linear(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2343]], requires_grad=True), Parameter containing:
tensor([0.9186], requires_grad=True)]


In [7]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:0.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 15.930012
Epoch  100/2000 Cost: 0.225004
Epoch  200/2000 Cost: 0.139039
Epoch  300/2000 Cost: 0.085917
Epoch  400/2000 Cost: 0.053092
Epoch  500/2000 Cost: 0.032808
Epoch  600/2000 Cost: 0.020273
Epoch  700/2000 Cost: 0.012528
Epoch  800/2000 Cost: 0.007741
Epoch  900/2000 Cost: 0.004784
Epoch 1000/2000 Cost: 0.002956
Epoch 1100/2000 Cost: 0.001827
Epoch 1200/2000 Cost: 0.001129
Epoch 1300/2000 Cost: 0.000697
Epoch 1400/2000 Cost: 0.000431
Epoch 1500/2000 Cost: 0.000266
Epoch 1600/2000 Cost: 0.000165
Epoch 1700/2000 Cost: 0.000102
Epoch 1800/2000 Cost: 0.000063
Epoch 1900/2000 Cost: 0.000039
Epoch 2000/2000 Cost: 0.000024


In [8]:
# 임의의 입력 4를 선어
new_var = torch.FloatTensor([4.0])

pred_y = model(new_var)
print("훈련 후 입력이 4일 떄의 예측값 : ", pred_y)

훈련 후 입력이 4일 떄의 예측값 :  tensor([7.9902], grad_fn=<ViewBackward0>)


In [9]:
# model의 parameters 확인
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9943]], requires_grad=True), Parameter containing:
tensor([0.0129], requires_grad=True)]


# nn.Module과 클래스로 linear regression 구현하기 (multi linear regression)

In [10]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(42)

In [34]:
# 데이터 
x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [47]:
model = nn.Linear(3, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.4457,  0.0961, -0.1875]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


In [48]:
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs):
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 20113.572266
Epoch  100/2000 Cost: 0.410002
Epoch  200/2000 Cost: 0.397077
Epoch  300/2000 Cost: 0.384827
Epoch  400/2000 Cost: 0.373219
Epoch  500/2000 Cost: 0.362216
Epoch  600/2000 Cost: 0.351808
Epoch  700/2000 Cost: 0.341933
Epoch  800/2000 Cost: 0.332585
Epoch  900/2000 Cost: 0.323727
Epoch 1000/2000 Cost: 0.315336
Epoch 1100/2000 Cost: 0.307384
Epoch 1200/2000 Cost: 0.299841
Epoch 1300/2000 Cost: 0.292709
Epoch 1400/2000 Cost: 0.285938
Epoch 1500/2000 Cost: 0.279529
Epoch 1600/2000 Cost: 0.273455
Epoch 1700/2000 Cost: 0.267706
Epoch 1800/2000 Cost: 0.262244
Epoch 1900/2000 Cost: 0.257078


In [20]:
# 결과 확인
new_var = torch.FloatTensor([73, 80, 75])
pred_y = model(new_var)
print("훈련 후 예측값: ", pred_y)

print(list(model.parameters()))

훈련 후 예측값:  tensor([153.0108], grad_fn=<ViewBackward0>)
[Parameter containing:
tensor([[0.7751, 0.7133, 0.5202]], requires_grad=True), Parameter containing:
tensor([0.3501], requires_grad=True)]


# 모델을 클래스로 구현하기기

In [49]:
# single linear regression

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)
    
model = LinearRegressionModel()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch: {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))
        
    

Epoch:    0/2000 Cost: 10.563588
Epoch:  100/2000 Cost: 0.163161
Epoch:  200/2000 Cost: 0.100823
Epoch:  300/2000 Cost: 0.062303
Epoch:  400/2000 Cost: 0.038499
Epoch:  500/2000 Cost: 0.023790
Epoch:  600/2000 Cost: 0.014701
Epoch:  700/2000 Cost: 0.009084
Epoch:  800/2000 Cost: 0.005614
Epoch:  900/2000 Cost: 0.003469
Epoch: 1000/2000 Cost: 0.002144
Epoch: 1100/2000 Cost: 0.001325
Epoch: 1200/2000 Cost: 0.000819
Epoch: 1300/2000 Cost: 0.000506
Epoch: 1400/2000 Cost: 0.000313
Epoch: 1500/2000 Cost: 0.000193
Epoch: 1600/2000 Cost: 0.000119
Epoch: 1700/2000 Cost: 0.000074
Epoch: 1800/2000 Cost: 0.000046
Epoch: 1900/2000 Cost: 0.000028
Epoch: 2000/2000 Cost: 0.000017


In [50]:
test = torch.FloatTensor([5])
test_result = model(test)
print(test_result)
print(list(model.parameters()))

tensor([9.9868], grad_fn=<ViewBackward0>)
[Parameter containing:
tensor([[1.9952]], requires_grad=True), Parameter containing:
tensor([0.0110], requires_grad=True)]


In [52]:
# multi linear regression

# 데이터
x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    
    def forward(self, x):
        return self.linear(x)
    
model = MultivariateLinearRegressionModel()

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    
    if epoch % 100 == 0:
        print('Epoch: {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost))

Epoch:    0/2000 Cost: 6240.712402
Epoch:  100/2000 Cost: 3.675513
Epoch:  200/2000 Cost: 3.499397
Epoch:  300/2000 Cost: 3.332561
Epoch:  400/2000 Cost: 3.174474
Epoch:  500/2000 Cost: 3.024679
Epoch:  600/2000 Cost: 2.882750
Epoch:  700/2000 Cost: 2.748296
Epoch:  800/2000 Cost: 2.620850
Epoch:  900/2000 Cost: 2.500140
Epoch: 1000/2000 Cost: 2.385702
Epoch: 1100/2000 Cost: 2.277272
Epoch: 1200/2000 Cost: 2.174541
Epoch: 1300/2000 Cost: 2.077169
Epoch: 1400/2000 Cost: 1.984925
Epoch: 1500/2000 Cost: 1.897483
Epoch: 1600/2000 Cost: 1.814616
Epoch: 1700/2000 Cost: 1.736091
Epoch: 1800/2000 Cost: 1.661669
Epoch: 1900/2000 Cost: 1.591135
Epoch: 2000/2000 Cost: 1.524280


In [ ]:
test = torch.FloatTensor([73, 80, 75])
test_result = model(test)
print(test_result)
print(list(model.parameters()))

tensor([152.7195], grad_fn=<ViewBackward0>)
[Parameter containing:
tensor([[0.6900, 0.6617, 0.6621]], requires_grad=True), Parameter containing:
tensor([-0.2455], requires_grad=True)]
