Linear Regression practice

In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(42)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)


tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [7]:
# 가중치 W초기화
W = torch.zeros(1, requires_grad=True)
print(W)

# 편향 b도 초기화
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [ ]:
# 가설 선언
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [9]:
# MSE 선언
cost = torch.mean((y_train - hypothesis) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [10]:
# SGD (Stochastic Gradient Descent)
optimizer = optim.SGD([W,b], lr = 0.01)
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b 업데이트
optimizer.step()

In [14]:
# 예제 
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

#모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs): 
    # H(x) 계산  (예상값 계산)
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((y_train - hypothesis) ** 2)
    
    #cost로 H(x) 개선
    # b, W의 .grad를 0으로 초기화 
    optimizer.zero_grad()
    # b, W의 .grad를 각각을 기준으로 미분하여 구함.
    cost.backward()
    # b, W 갱신
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{}, W: {:.3f}, b: {:.3f}, Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))


Epoch    0/1000, W: 0.187, b: 0.080, Cost: 18.666666
Epoch  100/1000, W: 1.746, b: 0.578, Cost: 0.048171
Epoch  200/1000, W: 1.800, b: 0.454, Cost: 0.029767
Epoch  300/1000, W: 1.843, b: 0.357, Cost: 0.018394
Epoch  400/1000, W: 1.876, b: 0.281, Cost: 0.011366
Epoch  500/1000, W: 1.903, b: 0.221, Cost: 0.007024
Epoch  600/1000, W: 1.924, b: 0.174, Cost: 0.004340
Epoch  700/1000, W: 1.940, b: 0.136, Cost: 0.002682
Epoch  800/1000, W: 1.953, b: 0.107, Cost: 0.001657
Epoch  900/1000, W: 1.963, b: 0.084, Cost: 0.001024
