### nn.Module

- Single Linear model
- Multi Linear model

In [ ]:
### Single ver.

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
#model = nn.Linear(input_dim, output_dim)
#cost = F.mse_loss(prediction, y_train)

torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
#단일 입력 - 단일 출력 선형 모델 설정
model = nn.Linear(1,1)

In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:6f}'. format(epoch, nb_epochs, cost.item()))

        

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [12]:
x_test = torch.FloatTensor([[4.0]])
pred_y = model(x_test)

print("test_y :",pred_y.detach().item())

test_y : 7.99890661239624


### Multi ver.

In [26]:
# import 항목 동일
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [27]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [28]:
model = nn.Linear(3, 1)
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True),
 Parameter containing:
 tensor([0.2710], requires_grad=True)]

In [29]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)
    # model.forward(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost {:6f}'.format(epoch, nb_epochs, cost.item()))
        

Epoch    0/2000 Cost 31667.599609
Epoch  100/2000 Cost 0.225993
Epoch  200/2000 Cost 0.223911
Epoch  300/2000 Cost 0.221941
Epoch  400/2000 Cost 0.220059
Epoch  500/2000 Cost 0.218271
Epoch  600/2000 Cost 0.216575
Epoch  700/2000 Cost 0.214950
Epoch  800/2000 Cost 0.213413
Epoch  900/2000 Cost 0.211952
Epoch 1000/2000 Cost 0.210559
Epoch 1100/2000 Cost 0.209230
Epoch 1200/2000 Cost 0.207967
Epoch 1300/2000 Cost 0.206762
Epoch 1400/2000 Cost 0.205618
Epoch 1500/2000 Cost 0.204529
Epoch 1600/2000 Cost 0.203481
Epoch 1700/2000 Cost 0.202486
Epoch 1800/2000 Cost 0.201539
Epoch 1900/2000 Cost 0.200634
Epoch 2000/2000 Cost 0.199770


In [30]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [31]:
x_test = torch.FloatTensor([[73, 80, 75]])
pred_y = model(x_test)

print("test_y :",pred_y.detach().item())

test_y : 151.23056030273438


### Model using Class

In [ ]:
# original ver.
model = nn.Linear(1,1)

In [ ]:
# class ver.
class LinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.linear(1,1)

    # forward 연산?
    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

In [ ]:
# original ver.
model = nn. Linear(3,1)

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.linear(3,1)

    def forward(self, x):
        return self.linear(x)
    
model = MultivariateLinearRegressionModel()

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [33]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [35]:
# class ver.
class LinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

In [36]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

nb_epochs = 2000
for epoch in range (nb_epochs+1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{}, Cost: {:6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000, Cost: 13.103541
Epoch  100/2000, Cost: 0.002791
Epoch  200/2000, Cost: 0.001724
Epoch  300/2000, Cost: 0.001066
Epoch  400/2000, Cost: 0.000658
Epoch  500/2000, Cost: 0.000407
Epoch  600/2000, Cost: 0.000251
Epoch  700/2000, Cost: 0.000155
Epoch  800/2000, Cost: 0.000096
Epoch  900/2000, Cost: 0.000059
Epoch 1000/2000, Cost: 0.000037
Epoch 1100/2000, Cost: 0.000023
Epoch 1200/2000, Cost: 0.000014
Epoch 1300/2000, Cost: 0.000009
Epoch 1400/2000, Cost: 0.000005
Epoch 1500/2000, Cost: 0.000003
Epoch 1600/2000, Cost: 0.000002
Epoch 1700/2000, Cost: 0.000001
Epoch 1800/2000, Cost: 0.000001
Epoch 1900/2000, Cost: 0.000000
Epoch 2000/2000, Cost: 0.000000


In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [38]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [42]:
class MultivariateLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegression()

In [43]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [44]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

        

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


In [47]:
test = torch.FloatTensor([[73, 80, 75]])
y_test = model(test)

print(y_test.item())

151.23056030273438
